<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        Higatra Property
    </title>
    <link rel="icon" href="images/logo.png" type="image/x-icon">


    <!-- slider stylesheet -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />

    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="css/bootstrap.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <!-- fonts style -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,600,700&display=swap" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="css/style.css" rel="stylesheet" />
    <!-- responsive style -->
    <link href="css/responsive.css" rel="stylesheet" />
    <style>
        .header-image {
            width: 100%;
            height: auto;
        }

        .container {
            display: block;
            gap: 20px;
            width: 80%;
            margin: 0 auto;
            padding-top: 50px;
            text-align: center;
            margin-top: 50px;
            margin-bottom: 50px;
            /* background: #000; */
        }

        .header {
            font-size: 36px;
            color: #b59a3b;
            font-weight: bold;
        }

        .content {
            font-size: 16px;
            color: #333;
            line-height: 1.6;
            max-width: 600px;
            margin: 0 auto;
        }

        .content a {
            color: #fff;
            text-decoration: underline;
            font-weight: bold;
        }

        .section {
            background-color: #B69957;
            padding: 50px 0;
            margin: auto;
        }

        .section h2 {
            font-size: 24px;
            color: #ffffff;
            font-weight: bold;
        }

        .section p {
            font-size: 16px;
            color: #ffffff;
            max-width: 600px;
            margin: 0 auto;
        }

        .section-2 p {
            font-size: 16px;
            color: #000;
            max-width: 600px;
            margin: 0 auto;
        }

        .section-2 {
            background-color: #fff;
            padding: 50px 0;
        }

        .section-2 h2 {
            font-size: 24px;
            color: #000;
            font-weight: bold;
        }

        .section-2 p {
            font-size: 16px;
            color: #000;
            max-width: 600px;
            margin: 0 auto;
        }

        .logo {
            display: block;
            margin: 20px auto;
        }

        .contact-button {
            background-color: #00b140;
            color: #fff;
            padding: 10px 20px;
            border-radius: 20px;
            text-decoration: none;
            display: inline-block;
            margin-top: 20px;
        }

        .contact-button i {
            margin-right: 10px;
        }

        .footer {
            margin-bottom: auto;
        }

        .section {
            padding: 20px 0;
            background-color: #B69957;
        }

        .container-3 {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }

        .text-center {
            text-align: center;
        }

        .text-justify {
            text-align: justify;
        }

        @media (max-width: 576px) {
            .container-3 {
                padding: 10px;
            }

            .text-center {
                font-size: 18px;
            }

            .text-justify {
                font-size: 14px;
            }
        }

        @media (min-width: 577px) and (max-width: 992px) {
            .container-3 {
                padding: 15px;
            }

            .text-center {
                font-size: 20px;
            }

            .text-justify {
                font-size: 16px;
            }
        }

        @media (min-width: 993px) {
            .container-3 {
                padding: 20px;
            }

            .text-center {
                font-size: 22px;
            }

            .text-justify {
                font-size: 18px;
            }
        }
    </style>
</head>

<body>

    <?php include "layout/navbar.html" ?>
    <div class="container" style="margin-top: 100px;">
        <div class="header" style="margin-bottom: 20px;">
            Higatra Properti
        </div>
        <div class="content">
            <p style="text-align: justify; color:#fff">
                <b style="color: #AA8D3F;">Higatra Property</b> adalah perusahaan kontruksi yang didirikan pada <b style="color: #AA8D3F;">>tahun 2017</b> oleh <b style="color: #AA8D3F;">Eko
                    Heri Supriyanto.</b> Berawal dari keresahan, Higatra hadir di Masyarakat dengan <b style="color: #AA8D3F;">harga bangun
                    menyesuaikan dan Komitmen produk inovasi dengan Garansi resmi 1 Tahun.</b>
            </p>
            <p style="text-align: justify; color:#fff">
                Mewujudkan Rumah Impian merupakan suatu kebanggan bagi kami dengan <b style="color: #AA8D3F;">mengatur tata letak, pencahayaan,
                    dan elemen desain dengan cermat, kami membantu Anda menciptakan ruang yang harmonis, menenangkan,
                    dan menginspirasi. </b>
            </p>
            <p style="text-align: justify; color:#FFF">
                Higatra Property siap memberikan pengalaman yang menyenangkan. Kami akan mengurus semuanya, mulai dari
                desain hingga pengawasan proyek sampai terbangun rumah impian anda.
            </p>
        </div>
    </div>
    <div class="section">
        <div class="container-3">
            <h2 class="text-center">
                Visi
            </h2>
            <p class="text-justify">
                Menjadi perusahaan konstruksi yang <b>mengedepankan kualitas dan jaminan produk terbaik di
                    Indonesia.</b> memberikan kontribusi positif bagi klien yang membutuhkan jasa bangun
                <b>BERGARANSI</b> di Indonesia.
            </p>
        </div>
    </div>
    <div class="section">
        <div class="container-3">
            <h2 class="text-center">
                Misi
            </h2>
            <p class="text-justify">
                Berusaha mengembangkan <b>produk pelayanan terbaik dan memberikan inovasi kreatif pada jasa kontruksi
                    serta</b> memberikan kontribusi positif bagi masyarakat tentang jasa bangun dan renovasi
                <b>BERGARANSI</b> di Indonesia.
            </p>
        </div>
    </div>
    <html>

    <head>

        <!-- <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet" /> -->
        <style>
            body {
                text-align: center;
                background-color: #000;
                margin: 0;
                padding: 0;
                width: 100%;
            }

            /* h1 {
                font-size: 2em;
                color: #333;
                margin-top: 20px;
            } */

            .container-2 {
                display: flex;
                justify-content: center;
                align-items: center;
                margin-top: 20px;
                margin-bottom: 2px;
            }

            .report {
                position: relative;
                margin: 0 80px;
                /* Increased margin for more spacing */
                text-align: center;
            }

            .report img {
                width: 300px;
                height: 400px;
                border: 1px solid #ddd;
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            }

            .report-title {
                font-size: 12px;
                color: #fff;
                margin-top: 10px;
            }

            .report-2 {
                position: relative;
                margin: 0 80px;
                /* Increased margin for more spacing */
                text-align: center;
            }

            .report-2 img {
                width: 400px;
                height: 300px;
                border: 1px solid #ddd;
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            }

            .report-2-title {
                font-size: 5px;
                color: #333;
                margin-top: 10px;
            }

            .nav-arrows {
                position: absolute;
                top: 50%;
                width: 100%;
                display: flex;
                justify-content: space-between;
                transform: translateY(-50%);
                border-width: 0 3px 3px 0;
            }

            .nav-arrows i {
                font-size: 2em;
                color: #f7ef8a;
                cursor: pointer;
                background-color: #333;
                border-radius: 50%;
                padding: 10px;
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
                transition: background-color 0.3s, color 0.3s;
            }

            .nav-arrows i:hover {
                background-color: #0056b3;
                color: #fff;
            }

            .nav-left {
                position: absolute;
                left: -60px;
            }

            .nav-right {
                position: absolute;
                right: -60px;
            }
        </style>
    </head>

    <!-- <body>
        <div class="container-2"> -->
    <!-- <div class="section-2"> -->
    <h2 class="text-center" style="color:#b59a3b; margin-top: 20px">
        LEGALITAS
    </h2>
    </div>
    </div>
    <?php
    include 'kon/koneksi.php';

    // Ambil data LPPD dan LKPD dari database
    $lppd_query = "SELECT * FROM reports WHERE report_type = 'bebas1'";
    $lppd_result = mysqli_fetch_all(mysqli_query($conn, $lppd_query), MYSQLI_ASSOC);

    $lkpd_query = "SELECT * FROM reports WHERE report_type = 'bebas2'";
    $lkpd_result = mysqli_fetch_all(mysqli_query($conn, $lkpd_query), MYSQLI_ASSOC);
    ?>

    <div class="section-2" style="background-color: #000;">
        <div class="container-2" style="background-color: #000; padding: 10px;">
            <div class="row">
                <div class="col-md-6">
                    <div class="report">
                        <div class="nav-arrows">
                            <i class="fas fa-arrow-left nav-left" onclick="changeImage('lppd', -1)"></i>
                            <i class="fas fa-arrow-right nav-right" onclick="changeImage('lppd', 1)"></i>
                        </div>
                        <img alt="Cover of LPPD report with government emblem and text" height="400" id="lppd" src="images/reports/<?= $lppd_result[0]['image_url']; ?>" width="300" />
                        <div class="report-title" id="lppd-title"><?= $lppd_result[0]['title']; ?></div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="report-2" , style="margin: 30px; margin-top:50px;">
                        <div class="nav-arrows" , style="margin:0px">
                            <i class="fas fa-arrow-left nav-left" onclick="changeImage('lkpd', -1)"></i>
                            <i class="fas fa-arrow-right nav-right" onclick="changeImage('lkpd', 1)"></i>
                        </div>
                        <img alt="Cover of LKPD report with government emblem and text" height="400" id="lkpd" src="images/reports/<?= $lkpd_result[0]['image_url']; ?>" width="300" />
                        <div class="report-title" id="lkpd-title"><?= $lkpd_result[0]['title']; ?></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        const images = {
            lppd: [
                <?php foreach ($lppd_result as $row): ?> {
                        src: "images/reports/<?= $row['image_url']; ?>",
                        title: "<?= $row['title']; ?>"
                    },
                <?php endforeach; ?>
            ],
            lkpd: [
                <?php foreach ($lkpd_result as $row): ?> {
                        src: "images/reports/<?= $row['image_url']; ?>",
                        title: "<?= $row['title']; ?>"
                    },
                <?php endforeach; ?>
            ]
        };

        let currentIndex = {
            lppd: 0,
            lkpd: 0
        };

        function changeImage(reportType, direction) {
            currentIndex[reportType] += direction;
            if (currentIndex[reportType] < 0) {
                currentIndex[reportType] = images[reportType].length - 1;
            } else if (currentIndex[reportType] >= images[reportType].length) {
                currentIndex[reportType] = 0;
            }
            document.getElementById(reportType).src = images[reportType][currentIndex[reportType]].src;
            document.getElementById(reportType + "-title").innerText = images[reportType][currentIndex[reportType]].title;
        }
    </script>



    <html>

    <head>
        <title>
            Partners
        </title>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet" />
        <style>
            .partners {
                font-size: 2em;
                font-weight: bold;
                color: #1a1a1a;
                margin-top: 20px;
            }

            .logos {
                margin: 20px 0;
            }

            .logos img {
                margin: 0 20px;
                height: 100px;
            }

            .description {
                font-size: 1.2em;
                margin: 40px auto;
                width: 80%;
                color: #fff;
            }

            .contact-button {
                background-color: #d4af37;
                color: #ffffff;
                padding: 15px 30px;
                border: none;
                border-radius: 5px;
                font-size: 1.2em;
                cursor: pointer;
                margin: 20px auto;
                box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
                display: flex;
                align-items: center;
                justify-content: center;
                width: fit-content;
            }

            .contact-button i {
                margin-right: 10px;
            }

            .social-icons {
                margin: 20px 0;
                margin-top: auto;
            }

            .social-icons a {
                font-size: 1.5em;
                margin: 0 10px;
                color: #ffffff;
                text-decoration: none;
            }

            .whatsapp-float {
                position: fixed;
                bottom: 20px;
                right: 20px;
                background-color: #25d366;
                color: #ffffff;
                padding: 10px 20px;
                border-radius: 25px;
                display: flex;
                align-items: center;
                font-size: 1em;
                cursor: pointer;
                z-index: 1000;
            }

            .whatsapp-float i {
                margin-right: 10px;
            }
        </style>
    </head>

    <!-- partner -->
    <section class="section_partner pb-5" style="background-color: #fff;">
        <div class="heading_container navy3 mb-2 ">
            <h2>Our Partners</h2>
        </div>
        <div class="slider slider_partner">
            <div class="slider-items slider-items_partner">
                <?php
                include 'kon/koneksi.php';
                $query = "SELECT * FROM partners";
                $result = mysqli_query($conn, $query);
                while ($row = mysqli_fetch_assoc($result)): ?>
                    <img src="images/partners/<?= $row['image_url']; ?>" alt="Partner">
                <?php endwhile; ?>
            </div>
        </div>
    </section>

    <body>
        <div class="section-3">
            <div class="container-3">



            </div>

            <a href="https://wa.me/62887729791118?text=Halo,%20saya%20tertarik%20dengan%20jasa%20Anda." target="_blank" class="whatsapp-float">
                <i class="fab fa-whatsapp" style="margin-right: 10px;"></i>
                HUBUNGI KAMI!
            </a>



            <footer>
                <div class="footer">
                    <div class="container">
                        <div class="row align-items-center row_footer">
                            <div class="col-md-3">
                                <div class="map">
                                    <iframe
                                        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3959.900066300759!2d113.84915147483633!3d-7.021031992980595!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dd9e70057ed749f%3A0x92004152aeafb8ed!2sHIGATRA%20PROPERTY!5e0!3m2!1sid!2sid!4v1726040814118!5m2!1sid!2sid"
                                        width="100%" height="100%" style="border:0;" allowfullscreen="" loading="lazy">
                                    </iframe>
                                </div>
                            </div>
                            <div class="col-md-3 isi_footer" style="margin-top: 2%;">
                                <h5>Address</h5>
                                <p class="small"><i class="fas fa-map-marker-alt"></i> Jln. Jokotole No.7000, Dusun Toros, Babbalan,
                                    Kec.
                                    Batuan, Kabupaten Sumenep, Jawa Timur 69416</p>
                            </div>
                            <div class="col-md-3 isi_footer" style="margin-bottom: 3%;">
                                <h5>Work hours</h5>
                                <p class="small"><i class="fas fa-clock"></i> Senin-Sabtu 08:00 - 16:00 WIB</p>
                            </div>
                            <div class="col-md-3 isi_footer" style="margin-bottom: 2%;">
                                <h5>Contact</h5>
                                <p class="small"><i class="fas fa-envelope"></i> higatrapropertyv@gmail.com<br>
                                    <i class="fas fa-phone"></i> +62 877 - 2979 - 1118
                                </p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col text-center social-icons">
                                <i class="fab fa-facebook"></i>
                                <i class="fab fa-youtube"></i>
                                <i class="fab fa-instagram"></i>
                                <i class="fab fa-tiktok"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>

            <!-- footer section -->
            <?php include "layout/footer.html" ?>
            <script src="js/jquery-3.4.1.min.js"></script>
            <script src="js/bootstrap.js"></script>
            <script src="js/index.js"></script>
    </body>

    </html>